spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/nettychat?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
netty:
  webport: 8090 # Websocket port
  bossThread: 1
  workerThread: 2
  keepalive: true # Socket parameter, connection warranty, default value is False. When this feature is enabled, TCP proactively detects the validity of idle connections. You can consider this feature as a heartbeat mechanism for TCP, and it is important to note that the default heartbeat interval is 7200s, or 2 hours. Netty Turn off this feature by default
  backlog: 1024 # Socket parameter, server accepts the queue length of the connection, and if the queue is full, the client connection will be rejected
  sndbuf: 10485760 # TCP data send buffer size.
  revbuf: 10485760 # TCP data receive buffer size.
  heart: 180 # Read timeout
  period: 10 # Cycle of re-hair
  serverName: iot-netty-chat
  initalDelay: 10 # Reset delay